{
    "文件加密系统": "File encry system",
    "登录": "login",
    "自动登录": " autoLog",
    "记住密码": "keepPw",
    "我的电脑": "My compute",
    "文件扫描": "File Scan",
    "审批管理": "Exam manage",
    "我的申请": "My apply",
    "更多工具": "More tools",
    "修改密码": "Change pw",
    "退出登录": "Log out",
    "请输入内容": "Please enter the content",
    "选择设置": "option",
    "主题设置": "theme",
    "帮助": "help",
    "基础信息": "Base message",
    "计算机名称": "computer name",
    "IP/MAC": "IP/MAC",
    "服务器IP地址": "server IP address",
    "版本": "version",
    "加密授权": "encry authoriza",
    "敏感信息识别授权": "message authoriza",
    "安全桌面授权": "safe desktop authoriza",
    "最后策略更新时间": "last update time",
    "手动更新策略": "manual update",
    "快捷操作": "Fast hand",
    "权限管理": "power MGT",
    "软件中心": "App apply",
    "文件内容识别": "File identify",
    "配置": "configuration",
    "扫描文件": "Scan file",
    "开始扫描": "start",
    "重新扫描": "again",
    "停止扫描": "stop",
    "扫描范围": "range",
    "搜索子文件夹": "search directory",
    "文件类型": "type",
    "仅搜索加密文件": "search encry file",
    "安全区域": "area",
    "全部": "all",
    "安全等级": "level",
    "Office文件(*.doc; *.docx; *.xls; *.xlsx; *.ppt; *.pptx)": "Office file (*.doc; *.docx; *.xls; *.xlsx; *.ppt; *.pptx)",
    "图像文件(*.jpg; *.jpeg; *.jpe; *.bmp; *.gif; *.png; *.tif; *.tiff)": "img file (*.jpg; *.jpeg; *.jpe; *.bmp; *.gif; *.png; *.tif; *.tiff)",
    "扫描准备就绪，请点击「开始扫描」": "Read please start",
    "序号": "id",
    "文件名称": "name",
    "文件夹": "path",
    "修改时间": "time",
    "大小/kb": "size/kb",
    "状态": "state",
    "描述": "des",
    "暂无数据": "no data",
    "待审批": "pend approval",
    "待执行": "pend perform",
    "已完成": "complete",
    "申请类型": "type",
    "解密申请": "decode apply",
    "使用设备": "use equipment",
    "发送邮件": "send mail",
    "查询": "search",
    "查看详情": "check the details",
    "取消申请": "cancel apply",
    "创建申请": "createApply",
    "申请解密": "apply decode",
    "申请外发": "apply send",
    "申请临时离线": "apply offline",
    "申请移动存储": "apply storage",
    "申请使用设备": "apply equipment",
    "申请打印": "apply print",
    "申请打印不带水印": "apply print nowater",
    "申请聊天工具传送文件": "apply chat send file",
    "申请复制到移动盘": "apply copy storage",
    "申请复制到网络盘": "apply copy drive",
    "申请刻录光盘": "apply burn a CD",
    "申请去除文档水印": "apply unwatermark documents",
    "时间": "time",
    "申请方式": "method",
    "审批人": "approver",
    "文件路径": "path",
    "区域": "area",
    "安全助手": "Safe helper",
    "系统检测": "System detection",
    "数据助手": "Data helper",
    "选项设置": "Option set",
    "常规选项": "base option",
    "安全密码设置": "safe pw set",
    "安全密码输入设置": "safe pw inp set",
    "账号设置": "account set",
    "解密申请设置": "decode set",
    "数据保存设置": "data save set",
    "加密功能选项": "encry option",
    "用户密码输入设置": "pw input set",
    "加密功能启用设置": "encry start set",
    "新密码": "new pw",
    "原密码": "original pw",
    "确认密码": "confirm pw",
    "滚动测试": "scroll test",
    "确定":  "confirm",
    "取消": "cancel",
    "更换主题": "Change theme",
    "蓝色": "blue",
    "绿色": "green",
    "粉色": "pink",
    "紫色": "purple",
    "配置快捷操作": "Set fast operation",
    "我的快捷操作": "My fast operation",
    "全部快捷操作端口": "All fast operation",
    "添加自定义快捷操作": "Add-define-fast-operation",
    "待添加": "to add",
    "自定义快捷操作": "Define fast operation",
    "名称": "name",
    "链接": "link",
    "图标": "icon",
    "请选择40x40px的png图片": "please select 40x40px 的png图片",
    "中文": "zh",
    "英文": "en",
    "扫描中：扫描到有": "scan start: scan",
    "扫描结束：扫描到有": "scan over: scan",
    "个文件。": "file",
    "文本": "text"
}